### ISSUE TITLE
edge case

### ISSUE THREAD

**Issue by revan-zhang** [thomasyimgit/memoize#2]
what if a function's result doesn't based on the order of the arguments? like:

```
function add(...args) { return args.reduce((a, b) => a + b, 0)}

add(1, 2) === add(2, 1)
```

could the memoize works well?

**Comment by revan-zhang** [comment]
Maybe should find a better way to store the key in cache?

**Comment by cyan33** [comment]
Good catch. But I think the memoize wrapper should not care about the sequence of the parameters. Since the rule of commutative law doesn't apply to most of the functions.

**Comment by revan-zhang** [comment]
Ah ha, I'm glad you can think about the different case of it.I think you are right about this case.

But how about the different type of it?

object always  store the key as a string, so these will be the same in cache:

```
add('1', '2') === add(1, 2) // false
```

**Comment by cyan33** [comment]
Good one. We do have to improve on this. Thanks for pointing out.

**Comment by cyan33** [comment]
On second thought tho, isn't the type checking thing the responsibility of the function itself, not of memoizer? And it's also not safe if we see '1' as 1.

**Comment by revan-zhang** [comment]
..... 
![image](https://user-images.githubusercontent.com/18140164/31802236-b911ef08-b512-11e7-9db0-460e79d3c530.png)

**Comment by cyan33** [comment]
![image](https://user-images.githubusercontent.com/13282699/31802465-63d26054-b51c-11e7-8517-a556d755eaca.png)
I think this better addresses the issue you have mentioned. Yes, I'll work on this later.

**Comment by cyan33** [comment]
https://github.com/thomasyimgit/memoize/commit/c23339a8839a99b6d417022ec98d8115d66fbbd7
This necessarily fixes the issue here.
